name = "BahBeuh"
author = "nistroy"
version = "2026-09-27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4715c72435e088e296cb81e53db5da0e1c33d1b8feeb173b1a64f9c115c67be7"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
